set(ECLIPSED_RUNTIME_ROOT "${CMAKE_SOURCE_DIR}/Source/Engine/EclipsedRuntime")

file(GLOB_RECURSE ECLIPSED_RUNTIME_SOURCES
    "${ECLIPSED_RUNTIME_ROOT}/*.cpp"
    "${ECLIPSED_RUNTIME_ROOT}/*.h"
    "${ECLIPSED_RUNTIME_ROOT}/*.hpp"
    "${ECLIPSED_RUNTIME_ROOT}/*.inl"
    "${CMAKE_CURRENT_SOURCE_DIR}/pch.h"
    )