set(GRAPHICS_ENGINE_ROOT "${CMAKE_SOURCE_DIR}/Source/Engines/GraphicsEngine")

file(GLOB_RECURSE GRAPHICS_ENGINE_SOURCES
    "${GRAPHICS_ENGINE_ROOT}/*.cpp"
    "${GRAPHICS_ENGINE_ROOT}/*.c"
    "${GRAPHICS_ENGINE_ROOT}/*.h"
    "${GRAPHICS_ENGINE_ROOT}/*.hpp"
    "${GRAPHICS_ENGINE_ROOT}/*.inl"
    "${CMAKE_CURRENT_SOURCE_DIR}/pch.h"
    )