set(NETWORK_ENGINE_ROOT "${CMAKE_SOURCE_DIR}/Source/Engine/EngineModules/NetworkEngine")

file(GLOB_RECURSE NETWORK_ENGINE_SOURCES
    "${NETWORK_ENGINE_ROOT}/*.cpp"
    "${NETWORK_ENGINE_ROOT}/*.h"
    "${NETWORK_ENGINE_ROOT}/*.hpp"
    "${NETWORK_ENGINE_ROOT}/*.inl"
    "${CMAKE_CURRENT_SOURCE_DIR}/pch.h"
    )

# list(REMOVE_ITEM NETWORK_ENGINE_SOURCES "${NETWORK_ENGINE_ROOT}/Client/Client.h")
# list(REMOVE_ITEM NETWORK_ENGINE_SOURCES "${NETWORK_ENGINE_ROOT}/Client/Client.cpp")